### ISSUE TITLE
Implementar login de usuário

### ISSUE THREAD

**Issue by lucaaas** [fga-gpp-mds/2018.1-Lacos-da-Alegria#114]
Eu, como usuário, desejo fazer login na aplicação para poder ter acesso aos recursos do sistema.

Critérios de aceitação:

- [ ] Exibir mensagem de erro em caso de e-mail/senha inválido.
- [ ] Redirecionar para página inicial quando o login for feito com sucesso.

**Comment by lucaaas** [comment]
Reabrindo, porque a issue não está resolvida.

**Comment by joaovitorml** [comment]
Backend finalizado e testado.
