### ISSUE TITLE
Implementar logout de usuário

### ISSUE THREAD

**Issue by lucaaas** [fga-gpp-mds/2018.1-Lacos-da-Alegria#115]
Eu como usuário desejo fazer o logout na aplicação para encerrar meu acesso aos recursos do sistema.

Critérios de aceitação:
- [x] Mensagem para confirmar a ação
- [x] Redirecionamento para página de Login

**Comment by lucaaas** [comment]
Reabrindo, porque a issue não está resolvida.

**Comment by joaovitorml** [comment]
Issue fixed together with #196.
