### ISSUE TITLE
Implementar fila de espera para usuários novatos

### ISSUE THREAD

**Issue by lucaaas** [fga-gpp-mds/2018.1-Lacos-da-Alegria#116]
Eu, como novato, gostaria de entrar em uma fila de espera para aguardar pela minha participação em uma atividade no hospital que eu escolhi.

- [ ] O último novato a se cadastrar entra no final da fila (não há sorteio)
- [ ] O novato não pode estar presente em mais de uma fila
- [ ] Os novatos no topo da fila de espera são selecionados para as visitas

**Comment by joaovitorml** [comment]
Issue resolvida.
