### ISSUE TITLE
Testar funcionalidades de usuário

### ISSUE THREAD

**Issue by lucaaas** [fga-gpp-mds/2018.1-Lacos-da-Alegria#141]
### Descrição

Eu, como desenvolvedor, gostaria de testar as funcionalidades para garantir a qualidade do produto.

### Critérios de aceitação

- [ ] Testar cadastro de usuário
- [ ] Testar edição de usuário
- [ ] Testar exclusão de usuário
- [ ] Testar login de usário
- [ ] Testar logout de usário

**Comment by rafaelmakaha** [comment]
A Issue será pausada por um momento devido a necessidade de se aplicar RestFull na aplicação.
