### ISSUE TITLE
Voluntário se inscrever em uma atividade - Backend

### ISSUE THREAD

**Issue by lucaaas** [fga-gpp-mds/2018.1-Lacos-da-Alegria#143]
### Descrição

Eu como voluntário gostaria de me inscrever na atividade que eu escolhi para participar da mesma.

### Critérios de aceitação

- [x] Usuário tem que estar logado para se inscrever
- [x] Não é possível se inscrever em duas atividades no mesmo horário
- [x] É possível se inscrever até 2hrs antes do início da atividade
- [x] As 2hs antes do início da atividade, a inscrição é bloqueada e só liberada a partir de segunda 00:00
- [x] Voluntário entrar na pré-lista de inscritos (Pré lista só existe entre Segunda 00:00 até Terça 23:59:59)

**Comment by lucaaas** [comment]
@renan601 @silvasara os critérios de aceitação foram atualizados.

**Comment by silvasara** [comment]
@lucaaas Em atividade não tem nenhum atributo que faça referência ao horário de seu inicio(veja o diagrama de classes), impossiblitando os três primeiros critérios de aceitação.
