### ISSUE TITLE
US10 - Visualizar status da inscrição

### ISSUE THREAD

**Issue by lucaaas** [fga-gpp-mds/2018.1-Lacos-da-Alegria#147]
### Descrição

Eu como voluntário gostaria de visualizar o status da minha inscrição na atividade para saber se minha vaga na atividade está reservada.

### Critérios de aceitação

- [x] Mostrar posição na fila de espera em tempo real.
- [x] Voluntário deve ter feito login antes.

**Comment by renan601** [comment]
Its done.
