### ISSUE TITLE
US16 - Fila de espera

### ISSUE THREAD

**Issue by lucaaas** [fga-gpp-mds/2018.1-Lacos-da-Alegria#154]
### Descrição

Eu, como voluntário, gostaria de entrar em uma fila de espera de uma atividade caso não haja mais vagas para poder participar dela caso alguém desista.

### Critérios de aceitação

- [ ] A lista é formada de acordo com o resultado sorteio.
- [ ] A lista pode conter voluntários e apoio.
- [ ] Se algum voluntário cancelar a participação na atividade, o primeiro voluntário da fila de espera é chamado.

**Comment by joaovitorml** [comment]
Issue resolvida.
