### ISSUE TITLE
Missing binding while executing up command on docker-compose

### ISSUE THREAD

**Issue by rafaelmakaha** [fga-gpp-mds/2018.1-Lacos-da-Alegria#183]
### Descrição

I'm getting the following output after running:
sudo docker-compose up

![image](https://user-images.githubusercontent.com/20361663/39786758-5181e7ba-52f8-11e8-9120-ccc49ada7b99.png)

**Comment by lucaaas** [comment]
Fechando, pois já foi resolvido.
