### ISSUE TITLE
ERROR: Version in "./docker-compose.yml" is unsupported

### ISSUE THREAD

**Issue by lucaaas** [fga-gpp-mds/2018.1-Lacos-da-Alegria#185]
Estou montando o ambiente do frontend e ao rodar o comando

`docker-compose build`

recebo o seguinte erro

![image](https://user-images.githubusercontent.com/20933647/39790498-ed8749fc-530c-11e8-8977-4a0e03da78f7.png)

**Comment by lucianosz7** [comment]
1º - Desinstalar a versão atual do docker.

2º- Intalar a versão 2.0 - sudo curl -L https://github.com/docker/compose/releases/download/1.10.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
3º - sudo chmod +x /usr/local/bin/docker-compose
4º - sudo ln -sd /usr/local/bin/docker-compose /usr/bin/docker-compose
5º - docker-compose --version

**Comment by lucaaas** [comment]
Caraca @lucianosz7 tu é muito top. Funcionou, vlws.
