### ISSUE TITLE
Fix "MergeableSelector" issue in src/pages/welcome/welcome.scss

### ISSUE THREAD

**Issue by caue96** [fga-gpp-mds/2018.1-Lacos-da-Alegria#192]
Merge rule `.body` with rule on line 7

https://codeclimate.com/github/fga-gpp-mds/2018.1-Lacos-da-Alegria/src/pages/welcome/welcome.scss#issue_5af9b2d7d779f100010009c6

**Comment by lucaaas** [comment]
Fechado, porque esse erro já foi corrigido.
