### ISSUE TITLE
Refatorar as funcionalidades de usuário no frontend

### ISSUE THREAD

**Issue by lucaaas** [fga-gpp-mds/2018.1-Lacos-da-Alegria#196]
### Descrição

Eu, como desenvolvedor, gostaria de refatorar as funcionalidades de usuário no frontend para fazer validações, testes e melhorar a usabilidade da aplicação.

##### Cadastrar usuário

* Campo Nome de Usuário
- [x] Deve aceitar somente os caracteres a-Z, 0-9, '_' (_underscore_) e '-' (hífen).
- [x] Deve ter entre 5 e 20 caracteres.
- [x] Deve ser único.

* Senha e confirmação de senha
- [x] Devem aceitar somente os caracteres a-Z e 0-9.
- [x] Deve ter entre 6 e 32 caracteres.
- [x] A senha e a confirmação de senha devem ser iguais.

* Email
- [x] Devem ter o formato email@email.com.
- [x] Deve ser único.

* Nome Completo
- [x] Deve aceitar somente os caracteres a-Z e espaço em branco.
- [x] Deve ter entre 3 e 50 caracteres.

* CPF
- [x] Deve seguir a validação usando o dígito de verificação.
- [x] Deve ser único.
- [x] Deve aceitar somente os caracteres 0-9.

* Data de Nascimento
- [x] Deve aceitar somente os caracteres 0-9.
- [x] A idade do usuário deve ser maior que 18 anos e menor que 120.

* WhatsApp
- [x] Deve aceitar somente os caracteres 0-9.
- [ ] Deve ter 11 caracteres, sendo dois para DDD.
- [x] O DDD digitado deve ser válido.

* Endereço
- [x] Deve ter entre 5 e 80 caracteres.

* Cidade Satélite
- [x] Deve aceitar somente os caracteres a-Z e 0-9.
- [x] Deve ter entre 4 e 40 caracteres.

#### Refatorações

- [x] A primeira vez que o servidor executa, não é possível mudar as páginas da Welcome deslizando o dedo.
- [x] Para todos os campos que o usuário preencher errado mostrar uma mensagem de erro.

##### Cadastrar usuário
- [x] Não é possível voltar para a tela de login depois de tocar em Cadastrar usuário.
- [x] Habilitar botão para a próxima página somente se todos os campos forem preenchidos corretamente.
- [x] Mudar nome do campo usuário para Nome de Usuário.
- [x] A primeira página deve conter apenas os campos (nessa ordem): Nome de Usuário, E-mail, senha e confimação de senha.
- [ ] O CPF deve ser mostrado no formato XXX.XXX.XXX-XX.
- [x] A Data de Nascimento deve ser mostrada no formato DD/MM/AAAA.
- [ ] Os campos DDD e WhatsApp devem ser apenas um, no formato (XX) XXXXXXXXXX.
- [ ] A segunda página deve conter apenas os campos (nessa ordem): Nome Completo, CPF, Data de Nascimento, Sexo e WhatsApp.
- [x] O campo Cidade Satélite não cobre todas as cidades.
- [x] Mudar nome do campo Preferência de Atividade para Hospital que deseja visitar.
- [ ] A terceira página deve conter apenas os campos (nessa ordem): Cidade Satélite, Endereço, Hospital que deseja visitar
- [x] Não é possível ler todas as opções do campo Como conheceu a Laços?.
- [ ] A última página deve conter apenas os campos (nessa ordem): Como conheceu a Laços e Desejo visitar instituições de caridade.
- [x] Os botões da última página devem seguir o padrão das outras páginas (um ao lado do outro).
- [x] Mudar o nome do botão Cancel das Pop-ups para Cancelar.
- [x] Cada página de cadastro deve ter um título que indica quais dados o usuário irá preencher.

##### Login
- [x] Colocar as labels Nome de Usuário e Senha nos campos.

##### Perfil de usuário
- [ ] Colocar a página Perfil no padrão do protótipo.
- [x] O CPF deve estar no formato XXX.XXX.XXX-XX.
- [x] A Data de Nascimento deve ser mostrada no formato DD/MM/AAAA.
- [x] O atributos devem ser mostrados em português.

##### Outros
- [x] No menu, existe um botão chamado Lista de Atividades que leva para alguma página. Mas a página inicial se chama Lista de Atividades. Se forem coisas diferentes, mudar o nome deste botão.
- [x] Ao fazer logout, o menu inferior continua aparecendo.

#### Testes
- [ ] Os testes devem ser feitos para todos os campos, testando suas validações, tanto no fluxo correto, quanto no incorreto.

**Comment by lucaaas** [comment]
Critérios de aceitação desmarcados por não estarem corretas ou não implementados:

* O DDD digitado deve ser válido.
* A segunda página deve conter apenas os campos (nessa ordem): Nome Completo, CPF, Data de Nascimento, Sexo e WhatsApp.
* A terceira página deve conter apenas os campos (nessa ordem): Cidade Satélite, Endereço, Hospital que deseja visitar.
* A última página deve conter apenas os campos (nessa ordem): Como conheceu a Laços e Desejo visitar instituições de caridade.
* Ao cadastrar um usuário que já existe, não é mostrada uma mensagem de erro.
* Não deixar borda dos campos de login verdes, pois passa a mensagem de que está correto, Mesmo quando não está.
* O atributos devem ser mostrados em português: Gênero não está português.

**Comment by lucaaas** [comment]
Reaberta, pois não está completa.

**Comment by renan601** [comment]
Colocamos um regex para validar o DDD.
Agora cadastrar com nome de usuário, email ou CPF repetido exibe uma mensagem de erro personalizada, falando qual deles é repetido.
Todos os atributos estão em Português.
A gente mexeu com a ordenação da página, que julgamos ficar melhor do jeito que fizemos, visualmente e intuitivamente.
Na primeira tem as informações básicas do usuário, na segunda tem informações adicionais do usuário e na terceira ficou localização e preferências.
