### ISSUE TITLE
Elaborar o documento de arquitetura

### ISSUE THREAD

**Issue by luizguilherme5** [fga-gpp-mds/2018.1-Lacos-da-Alegria#20]
Eu como desenvolvedor, gostaria de elaborar o documento de arquitetura, para definir a estrutura de arquitetura do sistema a ser desenvolvido

**Comment by joaovitorml** [comment]
Aguardando revisão. @Jullianaa @lucaaas

**Comment by joaovitorml** [comment]
Solved.

**Comment by joaovitorml** [comment]
Solved.
