### ISSUE TITLE
Vocês abandonaram a disciplina

### ISSUE THREAD

**Issue by RochaCarla** [fga-gpp-mds/2018.1-Lacos-da-Alegria#204]
no zenhub vcs só documentaram até a 9 sprint.

Ou,

vcs abandoram a disciplina e não avisaram

Ou,

vcs abandoram a metodologia 

Ou,

O scrum master está de férias e ninguém assumiu o papel

**Comment by lucaaas** [comment]
Boa noite professora, não abandonamos a disciplina e (infelizmente) não estou de férias. O que aconteceu foi que tinha algumas outras tarefas com maior prioridade. 

Um dos ocorridos (e já aproveitando para informá-la) foi que na última reunião optamos por demitir o Cauê e eu queria falar com ele antes de subir qualquer coisa. Inclusive, já falei com e já está tudo certo.

Peço desculpas pelo atraso e o Pull Request com a documentação em questão está em análise.
