### ISSUE TITLE
Ambiente de homologação

### ISSUE THREAD

**Issue by RochaCarla** [fga-gpp-mds/2018.1-Lacos-da-Alegria#205]
Onde está o ambiente de homologação de vcs?

se não tem, quando é a previsão de entrega?

**Comment by luizguilherme5** [comment]
Assim que chegar em casa compartilho sim

**Comment by luizguilherme5** [comment]
Professora @RochaCarla, os servidores de homologação e produção encontra-se hospedados no DigitalOcean usando um deploy do docker. 

Eles podem ser acessados em:
Produção: http://138.68.133.220:8000/api/
Homologação: http://138.68.144.77:8000/api/

Tive que subir os containeres novamente pois sofremos um ataque DDOS em um dos servidores (de acordo com o DigitalOcean, mas acredito que possa ter sido somente um acesso simultâneo muito grande). Agora estamos automatizando esse deploy com o GitHooks.

O servidor de homologação vai receber a branch 'release' criada a cada sprint, que será apresentada semanalmente ao nosso cliente. Já o servidor de produção será atualizado a cada iteração na 'master', que é uma versão aprovada pelo cliente e testada.

Todas essas branches já possuem uma integração contínua no TravisCI funcionando com testes unitários e linting configurados. Essa sprint estamos incorporando também testes de aceitação automáticos (end-to-end)

Sobre o aplicativo, estamos em processo de geração da build funcionando no celular (sei que estamos atrasados com isso) e o deploy no Google Play também está sendo feito, juntamente com a versão que estamos testando para realizar e documentar o benchmarking. 

Qualquer outra dúvida, estamos dispostos a resolvê-la e melhorar. Obrigado pelo feedback, nós de EPS conversamos com o pessoal de MDS hoje e absorvemos as críticas que a senhora realizou.
