### ISSUE TITLE
Usuário se inscrever em uma atividade - Frontend

### ISSUE THREAD

**Issue by silvasara** [fga-gpp-mds/2018.1-Lacos-da-Alegria#216]
### Descrição

Eu como voluntário gostaria de me inscrever na atividade que eu escolhi para participar da mesma.

### Critérios de aceitação

- [ ] Usuário tem que estar logado para se inscrever
- [ ] Não é possível se inscrever em duas atividades no mesmo horário
- [ ] É possível se inscrever até 2hrs antes do início da atividade
- [ ] As 2hs antes do início da atividade, a inscrição é bloqueada e só liberada a partir de segunda 00:00
- [ ] Voluntário entrar na pré-lista de inscritos (Pré lista só existe entre Segunda 00:00 até Terça 23:59:59)

**Comment by joaovitorml** [comment]
Issue resolvida.
