### ISSUE TITLE
Implementar restrição de permissões

### ISSUE THREAD

**Issue by lucaaas** [fga-gpp-mds/2018.1-Lacos-da-Alegria#218]
### Descrição

Eu, como desenvolvedor, gostaria de implementar restrição de permissões para que o usuário veja apenas o que diz respeito ao seu perfil.

### Critérios de aceitação

- [ ] O novato só pode ver sua posição na fila do hospital selecionado.
- [x] O voluntário pode ver e se inscrever nos eventos da semana.
- [x] As demais páginas os dois podem ver.

**Comment by RomuloSouza** [comment]
Issue solved in PR #213, waiting for review
