### ISSUE TITLE
Elaborar o guia de estilo

### ISSUE THREAD

**Issue by luizguilherme5** [fga-gpp-mds/2018.1-Lacos-da-Alegria#22]
Eu como desenvolvedor, gostaria de desenvolver e padronizar um documento para guiar o estilo de programação do projeto de desenvolvimento.

**Comment by joaovitorml** [comment]
Aguardando revisão. @lucaaas

**Comment by caue96** [comment]
O guia de estilo de vocês ficou bom, só senti falta de uma coisa. Alguns dos pontos que vocês falaram como deveria ser feito, vocês não colocaram alguns exemplos do errado. Coloquem exemplos errados também.

**Comment by lucaaas** [comment]
O tópico 3.2 diz que pode ser utilizado _tabs_ ou espaços. Definam apenas um.

**Comment by joaovitorml** [comment]
Aguardando revisão. @lucaaas

**Comment by joaovitorml** [comment]
Solved.
