### ISSUE TITLE
Resultado divergente

### ISSUE THREAD

**Issue by Jullianaa** [fga-gpp-mds/2018.1-Lacos-da-Alegria#227]
-------------------------------------------
O documento "resultados sprint 2"  no tópico **fechamento da sprint** está divergente do texto descrito em relação aos pontos. Confira no link:
[Fechamento da sprint 2](https://github.com/fga-gpp-mds/2018.1-Lacos-da-Alegria/blob/develop/docs/sprints/sprint02/results.md#11-fechamento-da-sprint)

**Comment by lucaaas** [comment]
Consertei esse erro no PR #229 .
