### ISSUE TITLE
Atualizar documentação da sprint 6

### ISSUE THREAD

**Issue by Jullianaa** [fga-gpp-mds/2018.1-Lacos-da-Alegria#228]
-------------------------------------------
Existem duas histórias descritas na sprint 5 que não foram concluídas e provavelmente foram realizadas nessa sprint, no entanto não conta na documentação que elas foram feitas, são elas:

[Configurar github pages #110](https://github.com/fga-gpp-mds/2018.1-Lacos-da-Alegria/issues/110)

[Implementar fila de espera para usuários novatos #116](https://github.com/fga-gpp-mds/2018.1-Lacos-da-Alegria/issues/116)

[Login #114 ](https://github.com/fga-gpp-mds/2018.1-Lacos-da-Alegria/issues/114)

[Logout #115 ](https://github.com/fga-gpp-mds/2018.1-Lacos-da-Alegria/issues/115)

**Comment by lucaaas** [comment]
@Jullianaa quais histórias foram concluídas e não conta na documentação? 

As issues #110 e #116, realmente não foram concluídas.
