### ISSUE TITLE
Refatorar o CSS - páginas depois após fazer o Login

### ISSUE THREAD

**Issue by lucaaas** [fga-gpp-mds/2018.1-Lacos-da-Alegria#234]
### Descrição

Eu, como desenvolvedor, gostaria de refatorar o CSS das páginas apresentadas após o Login para melhorar a usabilidade.

### Critérios de aceitação
- [x] Refatorar página de atividades
- [x] Refatorar página de perfil
- [x] Refatorar menu

**Comment by joaovitorml** [comment]
Issue resolvida.
