### ISSUE TITLE
Teste de usabilidade

### ISSUE THREAD

**Issue by lucaaas** [fga-gpp-mds/2018.1-Lacos-da-Alegria#247]
### Descrição

Eu, como PO, gostaria de testar a usabilidade do aplicativo para garantir a qualidade do mesmo.

### Critérios de aceitação

- [ ] Realizar com no mínimo 5 pessoas que não participam do projeto.
- [ ] Gerar um relatório.

**Comment by Jullianaa** [comment]
Aguardando a funcionalidade de mostrar posição na fila de espera.
