### ISSUE TITLE
Especificação Suplementar

### ISSUE THREAD

**Issue by luizguilherme5** [fga-gpp-mds/2018.1-Lacos-da-Alegria#35]
Eu como desenvolvedor, gostaria de fazer a Especificação Suplementar para documentar os requisitos não funcionais do projeto.

**Comment by Jullianaa** [comment]
Galera, revisei o que foi feito da especificação suplementar até o momento, achei bom apesar de ainda estar incompleto no entanto quando forem referenciar aos requisitos, lembrem que são requisitos  não funcionais.

**Comment by silvasara** [comment]
Teremos algum sistema de ajuda para o usuário e de documentação de usuário on-line?

**Comment by Jullianaa** [comment]
Como o cliente solicitou foco em usabilidade, sim. Para você entender melhor, esses tópicos de ajuda ao usuário como cards, mensagens auxiliares entram como critérios de aceitação, que são especificações das histórias de usuário, que dizem exatamente o que devem ser feito.

**Comment by renan601** [comment]
Corrigi o que foi pedido e estou mandando o pull request
