### ISSUE TITLE
EVM

### ISSUE THREAD

**Issue by luizguilherme5** [fga-gpp-mds/2018.1-Lacos-da-Alegria#38]
Eu como gerente, desejo criar o EVM (_Earned Value Management_ - Gestão de Valor Agregado) para gerir os custos do projeto.

**Comment by Jullianaa** [comment]
Galera, estamos com um problema para elaborar EVM, porque não escrevemos todas as histórias. O que vcs sugerem? Escrevemos na prox sprint, ou faremos reunião antes?

**Comment by lucaaas** [comment]
Fechando por que está pronta.
