### ISSUE TITLE
Definir criterios de aceitação e descrição das issues

### ISSUE THREAD

**Issue by luizguilherme5** [fga-gpp-mds/2018.1-Lacos-da-Alegria#39]
Eu como Scrum Master, desejo definir os critérios de aceitação e descrição das issues, para melhorar a visibilidade do projeto.

**Comment by lucaaas** [comment]
A issue está pronta e o resultado pode ser visto [aqui](https://github.com/fga-gpp-mds/2018.1-Lacos-da-Alegria/issues).
