### ISSUE TITLE
Refatorar documento de Visão

### ISSUE THREAD

**Issue by lucaaas** [fga-gpp-mds/2018.1-Lacos-da-Alegria#51]
Eu, como desenvolvedor, gostaria de refatorar o documento de visão para fazer as atualizações necessárias que condizem com a realidade do projeto.

**Comment by renan601** [comment]
Refatorei o tópico 5 com todas funcionalidades do app.
Esperando revisão para mandar o PR.

**Comment by lucaaas** [comment]
> Visualizar Hospitais da Semana - Permite que o usuário visualize os hospitais que receberão visitas na semana.

Essa funcionalidade só pode ser feita por voluntários. Os novatos apenas podem ver a sua situação no hospital que ele escolheu ao se cadastrar

**Comment by renan601** [comment]
Verdade, vou alterar

**Comment by lucaaas** [comment]
Closed because it's done and merged in develop branch.
