### ISSUE TITLE
US03 - Fazer Login

### ISSUE THREAD

**Issue by Jullianaa** [fga-gpp-mds/2018.1-Lacos-da-Alegria#71]
Eu como **usuario** desejo fazer **login na aplicacao** para poder **ter acesso aos recursos do sistema**.

- [ ] Opcao de entrar.
- [ ] Exibicao de mensagem de erro em caso de e-mail/senha invalido.
- [ ] Redirecionamento para pagina inicial.

**Comment by lucaaas** [comment]
Issue duplicada. Issue de referência #114
