### ISSUE TITLE
Lista de voluntários da atividade

### ISSUE THREAD

**Issue by Jullianaa** [fga-gpp-mds/2018.1-Lacos-da-Alegria#75]
### Descrição
Eu, como **usuário**, desejo **visualizar lista de voluntários na atividade escolhida** para **identificar minha posição na lista de espera e saber quem vai participar da atividade**.

### Critérios de aceitação

- [ ] A lista é criada após o sorteio
- [ ] Caso ainda tenham vagas, é possível um voluntário entrar na lista.

**Comment by joaovitorml** [comment]
Issue resolvida.
